name: docker-build

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
          password: ${{ secrets.DOCKER_HUB_USERNAME }}